name: cling
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - cmake=3.15.1
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gtest=1.8.1
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - notebook=6.0.0
  - xeus-cling=0.7.1